# Gitpod configuration. Learn more https://www.gitpod.io/docs/references/gitpod-yml

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dev Server
    init: yarn install && yarn build
    command: yarn dev
  - init: bash

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    name: Landing Site
    onOpen: open-browser
